apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: argocd  # Replace with your target namespace
spec:
  type: ClusterIP
  ports:
    - port: 3003       # The port that will be exposed internally
      targetPort: 3003 # The port on the container to forward traffic to
  selector:
    app: order-service  # Label selector to target the deployment

